SPACE       = "space"
TAB         = "punch"
S_TAB       = "funch"
ENTER       = "slap"
DEL         = "chuck"
BACKSPACE   = "back"
ESCAPE      = "fly"
AMPERSAND   = "amp"
APOSTROPHE  = "bing"
ASTERISK    = "star"
AT          = "lat"
BACKSLASH   = "slay"
BACKTICK    = "backtick"
BAR         = "bar"
CARET       = "hat"
COLON       = "coal"
HYPHEN      = "dash"
COMMA       = "drip"
DOLLAR      = "doll"
DOT         = "dot"
DQUOTE      = "quote"
EQUAL       = "chud"
EXCLAMATION = "bang"
HASH        = "hash"
PERCENT     = "per"
PLUS        = "plus"
QUESTION    = "quest"
SLASH       = "slash"
SQUOTE      = "smote"
TILDE       = "till"
UNDERSCORE  = "ray"
SEMICOLON   = "Shem"
LANGLE      = "lang"
RANGLE      = "rang"
LBRACE      = "lace"
RBRACE      = "race"
LBRACKET    = "lack"
RBRACKET    = "rack"
LPAREN      = "lark"
RPAREN      = "hype"
A = "Alpha"
B = "Bravo"
C = "Charlie"
D = "Delta"
E = "Echo"
F = "Foxtrot"
G = "Gumbo"
H = "Honda"
I = "Igloo"
J = "Juneau"
K = "Kilo"
L = "Lima"
M = "Monty"
N = "Ninja"
O = "Oscar"
P = "Papa"
Q = "Quinn"
R = "Robin"
S = "Soda"
T = "Tango"
U = "Urdu"
V = "Victor"
W = "Whiskey"
X = "X-ray"
Y = "Yankee"
Z = "Zulu"



CHARACTER_ALTERNATIVES = SPACE + " | " + AMPERSAND + " | " + APOSTROPHE + " | " + ASTERISK + " | " + AT + " | " + BACKSLASH + " | " + BACKTICK + " | " + BAR + " | " + CARET + " | " + COLON + " | " + HYPHEN + " | " + COMMA + " | " + DOLLAR + " | " + DOT + " | " + DQUOTE + " | " + EQUAL + " | " + EXCLAMATION + " | " + HASH + " | " + PERCENT + " | " + PLUS + " | " + QUESTION + " | " + SLASH + " | " + SQUOTE + " | " + TILDE + " | " + UNDERSCORE + " | " + SEMICOLON + " | " + LANGLE + " | " + RANGLE + " | " + LBRACE + " | " + RBRACE + " | " + LBRACKET + " | " + RBRACKET + " | " + LPAREN + " | " + RPAREN + " | " + A + " | " + B + " | " + C + " | " + D + " | " + E + " | " + F + " | " + G + " | " + H + " | " + I + " | " + J + " | " + K + " | " + L + " | " + M + " | " + N + " | " + O + " | " + P + " | " + Q + " | " + R + " | " + S + " | " + T + " | " + U + " | " + V + " | " + W + " | " + X + " | " + Y + " | " + Z + " | zero | one | two | three | four | five | six | seven | eight | nine"

CHARACTER_MAP = {   SPACE       : " ",
				    AMPERSAND   : "&",
				    APOSTROPHE  : "'",
				    ASTERISK    : "*",
				    AT          : "@",
				    BACKSLASH   : "\\",
				    BACKTICK    : "`",
				    BAR         : "|",
				    CARET       : "^",
				    COLON       : ":",
				    HYPHEN      : "-",
				    COMMA       : ",",
				    DOLLAR      : "$",
				    DOT         : ".",
				    DQUOTE      : "\"",
				    EQUAL       : "=",
				    EXCLAMATION : "!",
				    HASH        : "#",
				    PERCENT     : "%",
				    PLUS        : "+",
				    QUESTION    : "?",
				    SLASH       : "/",
				    SQUOTE      : "'",
				    TILDE       : "~",
				    UNDERSCORE  : "_",
				    SEMICOLON   : ";",
				    LANGLE      : "<",
				    RANGLE      : ">",
				    LBRACE      : "{",
				    RBRACE      : "}",
				    LBRACKET    : "[",
				    RBRACKET    : "]",
				    LPAREN      : "(",
				    RPAREN      : ")",
				    A : "a",
				    B : "b",
				    C : "c",
				    D : "d",
				    E : "e",
				    F : "f",
				    G : "g",
				    H : "h",
				    I : "i",
				    J : "j",
				    K : "k",
				    L : "l",
				    M : "m",
				    N : "n",
				    O : "o",
				    P : "p",
				    Q : "q",
				    R : "r",
				    S : "s",
				    T : "t",
				    U : "u",
				    V : "v",
				    W : "w",
				    X : "x",
				    Y : "y",
				    Z : "z" }